version: '3.8'

services:
  db:
    image: postgres:14.15-alpine
    container_name: db-postgres
    environment:
      POSTGRES_DB: go_social
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 192.168.1.1
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data: 